[package]
name = "unslice-dst"
version = "0.1.0"
authors = ["fnrir"]
edition = "2018"
rust-version = "1.54"
readme = "README.md"

[dependencies]

[features]
default = ["cast_macro_tt_muncher", "std"]
cast_impl_core_cstr = []
cast_macro_tt_muncher = []
std = ["cast_macro_tt_muncher"]
